services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://hamenja.ir/api
      - VITE_UPLOAD_URL=https://hamenja.ir/
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@database:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET_IN}
      - PORT=5000
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mongo:latest
    container_name: database
    command: [ "mongod", "--auth", "--bind_ip_all" ]
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
  uploads_data:

networks:
  app-network:
    driver: bridge
